apiVersion: v1
kind: Secret
metadata:
  name: yaba-api-secret
type: Opaque
data:
  connection-string: U2VydmVyPXlhYmEtbXNzcWwtc2VydmljZSwxNDMzO0RhdGFiYXNlPXlhYmE7VXNlciBJZD1TQTtQYXNzd29yZD1BJlZlcnlDb21wbGV4MTIzUGFzc3dvcmQ7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl
  mssql-sa-password: QSZWZXJ5Q29tcGxleDEyM1Bhc3N3b3Jk
  jwt-config-secret-key: dGhpcy1pcy1vbmx5LWZvci1kZXZlbG9wbWVudC1hbmQtaS1saWtlLWxvdHItYW5kLWdsYWRpYXRvcg==
# ---------------------------------
# not a good practice to store secrets on public repositories (or even private)
# but this is just for demonstration purposes. The best practice is to use a secret manager like Azure Key Vault