apiVersion: v1
kind: Service
metadata:
  name: yaba-api-service
spec:
  type: NodePort
  selector:
    app: yaba-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
# ---------------------------------
# type is NodePort because I want to expose the service outside the cluster
# targetPort is the port that the service will forward the request to
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cp-broker-service
spec:
  type: NodePort
  selector:
    app: kafka-cp-broker
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: yaba-worker-categorizer-service
spec:
  type: NodePort
  selector:
    app: yaba-worker-categorizer
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8081