apiVersion: v1
kind: Service
metadata:
  name: yaba-api-service
spec:
  type: NodePort
  selector:
    app: yaba-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
# ---------------------------------
# type is NodePort because I want to expose the service outside the cluster
# targetPort is the port that the service will forward the request to